---
title: "Covid-19 Research Project"
---

**Overview**

For our project we have chosen to analyze covid related data. As we all know, COVID-19 has impacted just about everyone around the world. Over the past two years, COVID-19 has filled hospitals worldwide and taken countless lives in the process. We want to look at government responses to see how certain countries handled the pandemic

**Data**

For our data analysis we have the data provided by Oxford titled Oxford covid government response variables. The main categories in this dataset that we will be utilizing includes countries, continents, dates (particularly daily dates),  total cases of covid-19, total number of covid-19 deaths, total number of vaccinated people, total number of fully vaccinated people, population, population density, median age, percentage of people 65 and older, and GDP per capita, and many others. We will also be utilizing data provided by Bloomberg. They have created resiliency scores for the 53 top economies in the world. 

**Modeling**

We plan to build multiple linear regression models. 

The first regression model's dependent variable will be monthly covid deaths.

The second regression model's dependent variable is the reproductive rate. This is essentially the spreadability of the virus itself.

The third regression involves the economic impact and our dependent variable will be quarterly GDP.


For all linear regression models, we are in the process of finding proper explanatory variables.


**Visualizations**

We are going to make visualizations using ggplot, plotly, and others to increase the readability of our findings. It is important to become educated on the factors that affect covid deaths in the event another global pandemic becomes present.We hope to display trends that may not be apparently obvious in the hopes that this will aid in the current pandemic and future health problems to come.




